@startuml
start
:Guest visits hotel website;
:Guest searches for available rooms;
if (Room available?) then (yes)
  :Selects a room;
  :Enters guest details;
  :Confirms reservation;
  :Receives confirmation;
else (no)
  :Shows "No rooms available";
endif
stop
@enduml

@startuml
start
:Guest arrives at the hotel;
:Provides reservation details;
if (Reservation found?) then (yes)
  :Staff verifies reservation;
  :Assigns room to the guest;
  :Guest receives room key;
  :Guest checks into the room;
else (no)
  :Staff checks room availability;
  if (Room available?) then (yes)
    :Creates a new reservation;
    :Assigns room to the guest;
    :Guest receives room key;
    :Guest checks into the room;
  else (no)
    :Inform guest "No rooms available";
  endif
endif
stop
@enduml

@startuml
start
:Guest visits hotel website or hotel counter;
:Guest searches for available rooms with specify date and type;
if (Room available?) then (yes)
  :Selects a room;
  :Enters guest details;
  :Confirms booking;
  ' :Ask how guest would like to pay cash, cheque or card;
  split
    :Choose Cash;
  split again
    :Choose Card;
  split again
    :Choose GPay;
  end split
    if (Payment done) then (yes)
    :Receives confirmation; 
    else (no)
    :Booking failed;
    endif
else (no)
  :Shows "No rooms available";
  :Ask for future reservation;
  if(Respond Yes) then (yes)
  :make future reservation;
  else (no)
  :Thank you;
  endif
endif
stop
@enduml
