@startuml

class Hotel {
  +String name
  +int stars
}

class HotelLocation{
  +String name
  +String Adress
  +String PhoneNumber
  +List<Room> rooms
}

class Room {
  +int roomNumber
  +String type
  +double pricePerNight
  +boolean isAvailable

  +isRoomAvailable():boolean
  +checkIn():boolean
  +checkOut():boolean
}

class RoomHouseKeeping{
  String Description
  Date StartDate
  int Duration

  addHouseKeeping():boolean
}

class RoomKey{
  +int RoomNumber
  +String Barcode
  +issueAt Date
  +boolean Active
  +boolean master
}

class Account{
  +String id
  +String password 
  +String status

  resetPassword():boolean
}

class Person{
  +String name
  +String Address
  +String email
  +String Phone
  +String AccountType
}

class HouseKeeper{
  assignToRoom():boolean
}

class Guest {
  +int totalRoomsCheckin
  +createBooking():boolean
}

class Receptionist{
  +createBooking():boolean
}


class Search{
  <b>Search</b>
  +searchRoom(type,startDate,endDate)
}

class RoomBooking {
  +int reservationID
  +Date checkInDate
  +Date checkOutDate
  +Room room
  +Guest guest
  +Payment payment
  +ReservationStatus status

  +confirmReservation(): void
  +cancelReservation(): void
}

 class Invoice{
   +double amount

   createBill():boolean
}

class BillTransaction {
  +double amount
  +Date paymentDate
  +status paymentStatus

  iniateTransaction():boolean
}

class CreditTransaction{
  -String nameOnCard
  -String code
}

class CheckTransaction{
  -String bankName
  -String checkNumber
}

class CashTransaction{
  -double Amount
}

enum RoomType{
  Standard
  Deluxe
  FamilySuite
  BusinessSuite
}

enum PaymentStatus {
  CONFIRMED
  CANCELLED
  PENDING
}

enum AccountType{
  Guest
  Receptionist
}

enum AccountStatus{
  Active
  Closed
  Canceled
  Blacklisted
}

Hotel "1" *-- "0..*" HotelLocation
HotelLocation "1" *-- "0..*" Room
'HotelLocation "1" -- "0..*" Reservation
'Reservation "1" -- "1" Room
RoomBooking "1" <-- "1" Guest
RoomBooking "1" <-- "1" Receptionist
'Guest "1" -- "0..*" Reservation
'Room "1" -- "0..1" Reservation
Room "1" *-- "0..1" RoomKey
Room "1" *-- "0..1" RoomHouseKeeping
HouseKeeper "1" --|> "*" Person
HouseKeeper --> RoomHouseKeeping
Person <|-- Guest
Person <|-- Receptionist
Account --> Person
Room ..|> Search
Receptionist ..|> Search
Guest ..|> Search


Invoice *-- RoomBooking
BillTransaction --* Invoice
BillTransaction <|-- CreditTransaction
BillTransaction <|-- CheckTransaction
BillTransaction <|-- CashTransaction

@enduml
